// apps/qwik/src/app.tsx
import {
  $,
  component$,
  useSignal,
  useStore,
} from '@builder.io/qwik'
import './app.css'
import {
  corePresetPlugins, Node, NodeData, PluginManager, Schema,
} from "@emrgen/carbon-core";
import{
  blockPresetPlugins
} from "@emrgen/carbon-blocks";

import {
  ImmutableNodeFactory
} from "@emrgen/carbon-react";
import {Predicate} from "@emrgen/types";

const plugins = [
  ...corePresetPlugins,
  ...blockPresetPlugins,
]

const pm = new PluginManager(plugins);
const schema = new Schema(pm.specs, new ImmutableNodeFactory());

const content: Node = schema.type('section').create([
  schema.type('title').create([
    schema.text('Hello, World! 1')!,
  ])!,

  schema.type('section').create([
    schema.type('title').create([
      schema.text('Hello, World! 2')!,
    ])!,
  ])!,
])!;

// const ChangeContext = createContextId<EventEmitter>('change')

const Block = {
  find(data: NodeData, fn: Predicate<NodeData>): any {
    if (fn(data)) return data;

    for (const child of data.children) {
      const result = Block.find(child, fn);
      if (result) return result;
    }

    return null
  }
}

export const App = component$(() => {
  const count = useSignal(content);
  const root = useStore(content.data)

  // const change = new EventEmitter()
  // useContextProvider(ChangeContext, change);

  const onChange = $(() => {
    console.log(root);
    const text = Block.find(root, n => n.name === 'text')
    console.log(text)
    text.textContent += '!'
  });

  return (
    <div>
      <button onClick$={() => {
        count.value++
        onChange();
      }}>Click Me</button>
     <div class={'carbon-app'}>
       <Renderer node={root} />
     </div>
    </div>
  )
});

interface RendererProps {
  node: NodeData;
}

const Section = component$((props: RendererProps) => {
  return (
    <div data-id={props.node.id} data-name={props.node.name}>
      {props.node.children.map((child) => (
        <Renderer node={child} key={child.id}/>
      ))}
    </div>
  )
})

const Title = component$((props: RendererProps) => {
  return (
    <div data-id={props.node.id} data-name={props.node.name}>
      {props.node.children.map((child) => (
        <Renderer node={child} key={child.id}/>
      ))}
    </div>
  )
})

const Text = component$((props: RendererProps) => {
  // const data = useStore(props.node.data)
  // const change = useContext(ChangeContext);
  //
  // useTask$(async ({cleanup}) => {
  //   const onChange = (node: Node) => {
  //     console.log('change', node.id.toString());
  //   }
  //
  //   change.on('change', onChange)
  //   cleanup(() => {
  //     change.off('change', onChange)
  //   })
  // });

  return (
    <span data-id={props.node.id} data-name={props.node.name}>
      {props.node.textContent}
    </span>
  )
})

const Renderer = component$((props: RendererProps) => {
  switch (props.node.name) {
    case 'section':
      return <Section node={props.node} />
    case 'title':
      return <Title node={props.node} />
    case 'text':
      return <Text node={props.node} />
    default:
      return null;
  }
})

// apps/vue/src/App.vue
<script setup lang="ts">
import {blockPresetPlugins} from '@emrgen/carbon-blocks';
import {Carbon, PinnedSelection, PluginManager, Schema} from '@emrgen/carbon-core';
import {VueNodeFactory, VueState} from '@emrgen/carbon-vue';
import CarbonNode from "./CarbonNode.vue";
import {provide, reactive, ref} from 'vue'
import Person from "./Person.vue";

const node = reactive({
  name: 'Person',
  text: "Hello, World!",
})


const rm = {
  'Person': Person
}

provide('renderManager', rm)


const plugins = [
  ...blockPresetPlugins,
]

const pm = new PluginManager(plugins)
const schema = new Schema(pm.specs, new VueNodeFactory())

const content = schema.type('section').create([
  schema.type('title').create([
    schema.text('Hello, World! 1')!,
  ])!,

  schema.type('section').create([
    schema.type('title').create([
      schema.text('Hello, World! 2')!,
    ])!,
  ])!,
])!;

const state = VueState.create(content, PinnedSelection.NULL)

const app = new Carbon(state, schema, pm)

provide('app', app);

// @ts-ignore
window.app = app


const counter = ref(0);


setTimeout(() => {
  app.cmd.SetContent(content.find(n => n.isText)!, 'Hello, World! 3').Dispatch();
  console.log('content', content.textContent)
}, 1000)


const data = reactive({
  counter,
  children: [1,2,3,4,5]
})

const update = () => {
  data.counter++
  data.children.push(data.children.length + 1)
  // counter.value = counter.value + 1
}


</script>

<template>
  <div id="app">
    <button @click="update">Update</button>
    {{data.counter}}
    <div v-for="child in data.children" :key="child">
      {{child}}
    </div>
<!--    <CarbonNode :node="app.content"/>-->
  </div>
</template>

<style scoped>

</style>
