// packages/carbon-react/src/hooks/useCarbon.tsx
import { createContext, useContext } from "react";
import {Carbon} from "@emrgen/carbon-core";

const InnerCarbonContext = createContext<Carbon>(null!);

export const CarbonContext = ({ app, children }) => {
  return (
    <InnerCarbonContext.Provider value={app}>
      <div className="carbon-app">{children}</div>
    </InnerCarbonContext.Provider>
  );
};

export const useCarbon = () => {
  return useContext(InnerCarbonContext);
};

// xpackages/carbon-solid/src/hooks/useCarbon.tsx
import { Carbon } from "@emrgen/carbon-core";
import { createContext, onMount, useContext } from "solid-js";
import { CarbonEvents } from "../components/index";

const InnerCarbonContext = createContext<Carbon>({} as Carbon);

export const CarbonContext = (props: { value: Carbon; children: any }) => {
  onMount(() => {
    props.value.mounted();
  });

  return (
    <InnerCarbonContext.Provider value={props.value}>
      <div class={"carbon-app"}>
        <CarbonEvents>{props.children}</CarbonEvents>
      </div>
    </InnerCarbonContext.Provider>
  );
};

export const useCarbon = () => {
  return useContext(InnerCarbonContext);
};
