// packages/carbon-react/src/components/CarbonEvents.tsx
import React from 'react'
import { useEventListeners, useSelectionChange } from '../hooks';
import {EventsIn} from "@emrgen/carbon-core";

// listen for dom event
const events: EventsIn[] = [
  EventsIn.beforeinput,
  EventsIn.input,
  EventsIn.keyUp,
  EventsIn.keyDown,
  EventsIn.click,
  EventsIn.mouseDown,
  EventsIn.mouseDown,
  EventsIn.mouseOver,
  EventsIn.mouseOut,
  EventsIn.mouseUp,
  EventsIn.dragStart,
  EventsIn.scroll,
  EventsIn.blur,
  EventsIn.focus,
  EventsIn.copy,
  EventsIn.cut,
  EventsIn.paste,
];


export function CarbonEvents(props) {

  useSelectionChange();
  const listeners = useEventListeners(events);

  return (
    <div className='carbon-app-events' {...listeners}>
      {props.children}
    </div>
  )
}

// xpackages/carbon-solid/src/components/CarbonEvents.tsx
import {CarbonEditor, EventsIn} from "@emrgen/carbon-core";
import {onCleanup} from "solid-js";
import {useCarbon} from "../hooks";

const defaultEvents: EventsIn[] = [
  EventsIn.beforeinput,
  EventsIn.input,
  EventsIn.keyUp,
  EventsIn.keyDown,
  EventsIn.click,
  EventsIn.mouseDown,
  EventsIn.mouseOver,
  EventsIn.mouseOut,
  EventsIn.mouseUp,
  EventsIn.scroll,
  EventsIn.blur,
  EventsIn.focus,
  EventsIn.paste,
];

// prevent default for some events
const preventDefaultEvents = {
  [EventsIn.keyDown]: (e) => {
    if (e.key === 'Enter') {
      return true;
    }

    if (e.key === 'Backspace') {
      return true;
    }

    if (e.key === 'Delete') {
      return true;
    }

    if (e.key === 'input') {
      return true;
    }

    if (e.key === 'beforeInput') {
      return true;
    }

    return false;
  },
};

const eventWrapper = (event) => {
  return {
    ...event,
    nativeEvent: event,
    stopPropagation: () => {
      event.stopPropagation();
    },
    preventDefault: () => {
      event.preventDefault();
    }
  }
}

const handlers = (app: CarbonEditor) => {
  return defaultEvents.reduce(
    (o, eventType) => ({
      ...o,
      [(`on${eventType}`).toLowerCase()]: (event: Event) => {
        // console.log('xxx', eventType, event);
        if (preventDefaultEvents[eventType]?.(event)) {
          event.preventDefault();
        }
        // console.log('fired event', eventType, event)

        app.onEvent(eventType, eventWrapper(event));
      },
    }),
    {}
  );
}

export const CarbonEvents = (props) => {
  const app = useCarbon();

  const onSelectionChange = (event: Event) => {
    app.onEvent(EventsIn.selectionchange, event);
  }

  const onSelectionStart = (event: Event) => {
    app.onEvent(EventsIn.selectstart, event)
  }

  document.addEventListener(EventsIn.selectionchange, onSelectionChange);
  document.addEventListener(EventsIn.selectstart, onSelectionStart);
  onCleanup(() => {
    document.removeEventListener(EventsIn.selectionchange, onSelectionChange);
    document.removeEventListener(EventsIn.selectstart, onSelectionStart);
  })

  return (
    <div class={'carbon-app-events'} {...handlers(app)}>
      {props.children}
    </div>
  )
}
