// packages/carbon/src/hooks/useCarbon.tsx
import { createContext, useContext, useEffect, useState } from "react";
import { Carbon } from "../core/Carbon";

const InnerCarbonContext = createContext<Carbon>(null!);

export const CarbonContext = ({ app, children }) => {
  return (
    <div className="carbon-app">
      <InnerCarbonContext.Provider value={app}>
        {children}
      </InnerCarbonContext.Provider>
    </div>
  );
};

export const useCarbon = () => {
  return useContext(InnerCarbonContext);
};

// packages/carbon-solid/src/hooks/useCarbon.tsx
import {createContext, useContext} from "solid-js";
import {Carbon} from "@emrgen/carbon-core";

const InnerCarbonContext = createContext<Carbon>({} as Carbon);

export const CarbonContext = (props: {value: Carbon, children: any}) => {
  return (
    <InnerCarbonContext.Provider value={props.value}>
      {props.children}
    </InnerCarbonContext.Provider>
  )
}

export const useCarbon = () => {
  return useContext(InnerCarbonContext);
}
