// packages/carbon-solid/src/hooks/useCarbon.tsx
import {createContext, useContext} from "solid-js";
import {Carbon} from "@emrgen/carbon-core";

const InnerCarbonContext = createContext<Carbon>({} as Carbon);

export const CarbonContext = (props: {value: Carbon, children: any}) => {
  return (
    <InnerCarbonContext.Provider value={props.value}>
      {props.children}
    </InnerCarbonContext.Provider>
  )
}

export const useCarbon = () => {
  return useContext(InnerCarbonContext);
}

// packages/carbon-react/src/hooks/useCarbon.tsx
import { createContext, useContext } from "react";
import {Carbon} from "@emrgen/carbon-core";

const InnerCarbonContext = createContext<Carbon>(null!);

export const CarbonContext = ({ app, children }) => {
  return (
    <InnerCarbonContext.Provider value={app}>
      <div className="carbon-app">{children}</div>
    </InnerCarbonContext.Provider>
  );
};

export const useCarbon = () => {
  return useContext(InnerCarbonContext);
};
